apiVersion: v1
kind: Pod
metadata:
  name: poi-secret
  namespace: api
spec:
  containers:
  - name: poi
    image: redis
    volumeMounts:
    - name: poisecret
      mountPath: "/etc/poisecret"
      readOnly: true
  volumes:
  - name: poisecret
    secret:
      secretName: secrets
      items:
      - key: username
        path: my-group/my-username