apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-poi-img
  namespace: ch5
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi-container
        image: registrybwj5358.azurecr.io/poi:1.0
        env:
        - name: SQL_USER
          value: "sqladminbWj5358"
        - name: SQL_PASSWORD
          value: "bN1uq3Fc9"
        - name: SQL_SERVER
          value: "sqlserverbwj5358.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 80