apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: team11aksvault
spec:
  provider: azure
  parameters:
    keyvaultName: "team11aksvault"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "09b50902-a23f-46a2-ad56-0bad74b87485" # The clientId of the addon-created managed identity
    objects:  |
      array:
        - |
          objectName: <secret-name>       # In this example, 'ExampleSecret'   
          objectType: secret              # Object types: secret, key or cert          
    tenantId: "2a57965a-c84c-4b66-98e5-6d51be0138dc"               # the tenant ID containing the Azure Key Vault instance