apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  SQL_USER: sqladminbWj5358
  SQL_PASSWORD: bN1uq3Fc9
  SQL_SERVER: sqlserverbwj5358.database.windows.net
  SQL_DBNAME: mydrivingDB